//
// Created by lenovo on 26-7-30.
//

#ifndef MACHINECMD_TEXT_H
#define MACHINECMD_TEXT_H

#include <stdint.h>

/**
 * @brief LCD 原始显示文案。
 *
 * ST7920 的内置中文字库按 GB2312 编码取字模，所以中文不要直接写 UTF-8
 * 字符串。这里统一用 data + len 记录待发送到 LCD 的原始字节。
 */
typedef struct
{
    const uint8_t *data; // GB2312 中文字节或 ASCII 字节
    uint8_t len;         // 字节长度，LCD 单行最大 16 字节
} MachineCmdText_s;

extern const MachineCmdText_s machine_cmd_text_title;
extern const MachineCmdText_s machine_cmd_text_init;
extern const MachineCmdText_s machine_cmd_text_eeprom;
extern const MachineCmdText_s machine_cmd_text_ready;
extern const MachineCmdText_s machine_cmd_text_system_ready;
extern const MachineCmdText_s machine_cmd_text_any_key_start;
extern const MachineCmdText_s machine_cmd_text_standby;
extern const MachineCmdText_s machine_cmd_text_conc;
extern const MachineCmdText_s machine_cmd_text_volume;
extern const MachineCmdText_s machine_cmd_text_prep_title;
extern const MachineCmdText_s machine_cmd_text_prep_step1;
extern const MachineCmdText_s machine_cmd_text_prep_step2;
extern const MachineCmdText_s machine_cmd_text_prep_step3;
extern const MachineCmdText_s machine_cmd_text_current_conc_unit;
extern const MachineCmdText_s machine_cmd_text_current_volume_unit;
extern const MachineCmdText_s machine_cmd_text_target_conc_unit;
extern const MachineCmdText_s machine_cmd_text_disp_title;
extern const MachineCmdText_s machine_cmd_text_bottle;
extern const MachineCmdText_s machine_cmd_text_saved;
extern const MachineCmdText_s machine_cmd_text_target;
extern const MachineCmdText_s machine_cmd_text_prep_volume;
extern const MachineCmdText_s machine_cmd_text_raw_med;
extern const MachineCmdText_s machine_cmd_text_concentration;
extern const MachineCmdText_s machine_cmd_text_volume_prefix;
extern const MachineCmdText_s machine_cmd_text_current_conc;
extern const MachineCmdText_s machine_cmd_text_target_conc;
extern const MachineCmdText_s machine_cmd_text_start_next_confirm;
extern const MachineCmdText_s machine_cmd_text_start_next_step;
extern const MachineCmdText_s machine_cmd_text_start_prep;
extern const MachineCmdText_s machine_cmd_text_remaining_prefix;
extern const MachineCmdText_s machine_cmd_text_disp_start;
extern const MachineCmdText_s machine_cmd_text_current_measure;
extern const MachineCmdText_s machine_cmd_text_input_over_left;
extern const MachineCmdText_s machine_cmd_text_number_input;
extern const MachineCmdText_s machine_cmd_text_start;
extern const MachineCmdText_s machine_cmd_text_prep_run;
extern const MachineCmdText_s machine_cmd_text_prep_measure;
extern const MachineCmdText_s machine_cmd_text_activity;
extern const MachineCmdText_s machine_cmd_text_wait_activity;
extern const MachineCmdText_s machine_cmd_text_activity_timeout;
extern const MachineCmdText_s machine_cmd_text_countdown;
extern const MachineCmdText_s machine_cmd_text_pause_hint;
extern const MachineCmdText_s machine_cmd_text_pause_reset_hint;
extern const MachineCmdText_s machine_cmd_text_put_tank;
extern const MachineCmdText_s machine_cmd_text_start_ok;
extern const MachineCmdText_s machine_cmd_text_disp_run;
extern const MachineCmdText_s machine_cmd_text_pump2;
extern const MachineCmdText_s machine_cmd_text_progress_prefix;
extern const MachineCmdText_s machine_cmd_text_dont_move;
extern const MachineCmdText_s machine_cmd_text_paused_title;
extern const MachineCmdText_s machine_cmd_text_prep_paused;
extern const MachineCmdText_s machine_cmd_text_disp_paused;
extern const MachineCmdText_s machine_cmd_text_start_continue;
extern const MachineCmdText_s machine_cmd_text_reset_stop;
extern const MachineCmdText_s machine_cmd_text_clean_title;
extern const MachineCmdText_s machine_cmd_text_clean_pipe;
extern const MachineCmdText_s machine_cmd_text_pump1_run;
extern const MachineCmdText_s machine_cmd_text_waste_cup;
extern const MachineCmdText_s machine_cmd_text_manual;
extern const MachineCmdText_s machine_cmd_text_last;
extern const MachineCmdText_s machine_cmd_text_reset_exit_manual;
extern const MachineCmdText_s machine_cmd_text_on;
extern const MachineCmdText_s machine_cmd_text_off;
extern const MachineCmdText_s machine_cmd_text_full_colon;
extern const MachineCmdText_s machine_cmd_text_key_wi;
extern const MachineCmdText_s machine_cmd_text_key_wo;
extern const MachineCmdText_s machine_cmd_text_manual_switch_hint;
extern const MachineCmdText_s machine_cmd_text_in_tank;
extern const MachineCmdText_s machine_cmd_text_out_tank;
extern const MachineCmdText_s machine_cmd_text_needle_in;
extern const MachineCmdText_s machine_cmd_text_needle_out;
extern const MachineCmdText_s machine_cmd_text_draw_med;
extern const MachineCmdText_s machine_cmd_text_exhaust;
extern const MachineCmdText_s machine_cmd_text_remote;
extern const MachineCmdText_s machine_cmd_text_remote_title;
extern const MachineCmdText_s machine_cmd_text_remote_takeover;
extern const MachineCmdText_s machine_cmd_text_remote_pause;
extern const MachineCmdText_s machine_cmd_text_remote_reset;
extern const MachineCmdText_s machine_cmd_text_remote_pause_first;
extern const MachineCmdText_s machine_cmd_text_remote_paused;
extern const MachineCmdText_s machine_cmd_text_remote_start_continue;
extern const MachineCmdText_s machine_cmd_text_wait_host;
extern const MachineCmdText_s machine_cmd_text_wait_auth;
extern const MachineCmdText_s machine_cmd_text_remote_switching;
extern const MachineCmdText_s machine_cmd_text_local_takeover;
extern const MachineCmdText_s machine_cmd_text_remote_key_request;
extern const MachineCmdText_s machine_cmd_text_water_in;
extern const MachineCmdText_s machine_cmd_text_med_in;
extern const MachineCmdText_s machine_cmd_text_water_out;
extern const MachineCmdText_s machine_cmd_text_med_out;
extern const MachineCmdText_s machine_cmd_text_idle;
extern const MachineCmdText_s machine_cmd_text_alarm;
extern const MachineCmdText_s machine_cmd_text_fault;
extern const MachineCmdText_s machine_cmd_text_locked;
extern const MachineCmdText_s machine_cmd_text_rst_alarm;
extern const MachineCmdText_s machine_cmd_text_ui_device_standby;
extern const MachineCmdText_s machine_cmd_text_ui_prep_disp;
extern const MachineCmdText_s machine_cmd_text_ui_select_bottle_count;
extern const MachineCmdText_s machine_cmd_text_ui_one_bottle;
extern const MachineCmdText_s machine_cmd_text_ui_two_bottle;
extern const MachineCmdText_s machine_cmd_text_ui_press_1_or_2;
extern const MachineCmdText_s machine_cmd_text_ui_input_med_volume;
extern const MachineCmdText_s machine_cmd_text_ui_start_confirm;
extern const MachineCmdText_s machine_cmd_text_ui_prepare_ready_title;
extern const MachineCmdText_s machine_cmd_text_ui_put_tank_1;
extern const MachineCmdText_s machine_cmd_text_ui_water_cup_ready;
extern const MachineCmdText_s machine_cmd_text_ui_start_continue;
extern const MachineCmdText_s machine_cmd_text_ui_auto_prepare;
extern const MachineCmdText_s machine_cmd_text_ui_step;
extern const MachineCmdText_s machine_cmd_text_ui_in_tank_run;
extern const MachineCmdText_s machine_cmd_text_ui_insert_needle_run;
extern const MachineCmdText_s machine_cmd_text_ui_draw_water;
extern const MachineCmdText_s machine_cmd_text_ui_water_fill;
extern const MachineCmdText_s machine_cmd_text_ui_wait;
extern const MachineCmdText_s machine_cmd_text_ui_activity_check;
extern const MachineCmdText_s machine_cmd_text_ui_stable_read;
extern const MachineCmdText_s machine_cmd_text_ui_remaining;
extern const MachineCmdText_s machine_cmd_text_ui_check_done;
extern const MachineCmdText_s machine_cmd_text_ui_calculating;
extern const MachineCmdText_s machine_cmd_text_ui_bottle_1_done;
extern const MachineCmdText_s machine_cmd_text_ui_bottle_2_done;
extern const MachineCmdText_s machine_cmd_text_ui_change_tank;
extern const MachineCmdText_s machine_cmd_text_ui_put_tank_2;
extern const MachineCmdText_s machine_cmd_text_ui_start_reset_short;
extern const MachineCmdText_s machine_cmd_text_ui_auto_exhaust;
extern const MachineCmdText_s machine_cmd_text_ui_pump2_run;
extern const MachineCmdText_s machine_cmd_text_ui_pipe_flush;
extern const MachineCmdText_s machine_cmd_text_ui_pump1_run;
extern const MachineCmdText_s machine_cmd_text_ui_progress;
extern const MachineCmdText_s machine_cmd_text_ui_prepare_done;
extern const MachineCmdText_s machine_cmd_text_ui_concentration;
extern const MachineCmdText_s machine_cmd_text_ui_wait_dispense;
extern const MachineCmdText_s machine_cmd_text_ui_disp_setting;
extern const MachineCmdText_s machine_cmd_text_ui_input;
extern const MachineCmdText_s machine_cmd_text_ui_start_begin;
extern const MachineCmdText_s machine_cmd_text_ui_disp_running;
extern const MachineCmdText_s machine_cmd_text_ui_done;
extern const MachineCmdText_s machine_cmd_text_ui_aborting;
extern const MachineCmdText_s machine_cmd_text_ui_rail_home;
extern const MachineCmdText_s machine_cmd_text_ui_activity_label;
extern const MachineCmdText_s machine_cmd_text_ui_volume_label;
extern const MachineCmdText_s machine_cmd_text_ui_bottle1_label;
extern const MachineCmdText_s machine_cmd_text_ui_bottle2_label;
extern const MachineCmdText_s machine_cmd_text_debug_title;
extern const MachineCmdText_s machine_cmd_text_debug_idle_rail;
extern const MachineCmdText_s machine_cmd_text_debug_idle_pump;
extern const MachineCmdText_s machine_cmd_text_debug_idle_exit;
extern const MachineCmdText_s machine_cmd_text_debug_tank_forward;
extern const MachineCmdText_s machine_cmd_text_debug_tank_backward;
extern const MachineCmdText_s machine_cmd_text_debug_needle_forward;
extern const MachineCmdText_s machine_cmd_text_debug_needle_backward;
extern const MachineCmdText_s machine_cmd_text_debug_clear_needle;
extern const MachineCmdText_s machine_cmd_text_debug_clear_tank;
extern const MachineCmdText_s machine_cmd_text_debug_water_in;
extern const MachineCmdText_s machine_cmd_text_debug_water_out;
extern const MachineCmdText_s machine_cmd_text_debug_med_in;
extern const MachineCmdText_s machine_cmd_text_debug_med_out;
extern const MachineCmdText_s machine_cmd_text_debug_pump_enabling;
extern const MachineCmdText_s machine_cmd_text_debug_action_error;
extern const MachineCmdText_s machine_cmd_text_debug_fault_exit;

#endif //MACHINECMD_TEXT_H
